### ISSUE TITLE
Research the AWS SDK for Java

### ISSUE THREAD

**Issue by mrinoldo** [aaronlewis54321/Software_Engineering#11]
- [x] What is the AWS SDK for Java?
- [x] What Java APIs are included that may be useful?
- [x] Are there IDE plugins or add-ons that may be helpful in writing code/ communicating with the database?

**Comment by mbouh1** [comment]
- the AWS SDK for java allows for communication to be available from our java application to the AWS platform
- The SDK is available on the amazon website  https://aws.amazon.com/sdk-for-java/
- Their are many API's that are useful such as CreateTopic which allows for us to create a topic which notifications can be posted to
- I wasn't able to find any plugins for netbeans but their were some plugins for eclipse

**Comment by mrinoldo** [comment]
Maybe add a bit more specifics as far as potentially useful API's that we can integrate?
