### ISSUE TITLE
Modifying user information stored in the database

### ISSUE THREAD

**Issue by mrinoldo** [aaronlewis54321/Software_Engineering#13]
- [ ] Research which AWS SDK Java APIs will be useful for sending/modifying data?
- [ ] What format will data be transmitted in?
- [ ] What data will need to be modified?
- [ ] In which tables in the database?
- [ ] Utilize AWS SDK Java API reference documentation-
https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/index.html

**Comment by aaronlewis54321** [comment]
[https://app.zenhub.com/files/142712430/cd6d95e0-2561-41ef-af9c-26a0f149e4bf/download](https://app.zenhub.com/files/142712430/cd6d95e0-2561-41ef-af9c-26a0f149e4bf/download)

Determined through my conversations with a member of the database group that we will be able to use JDBC to connect to their MySQL database that is hosted in AWS directly. The document that I have uploaded here answers all of the questions in the task, and contains links that will help us when we are establishing out connection to the database, and when we are exporting data from the database to a CSV
