### ISSUE TITLE
Research how data will be exported into CSV

### ISSUE THREAD

**Issue by mrinoldo** [aaronlewis54321/Software_Engineering#14]
- [x] Research available Java libraries for exporting CSV.
- [x] Which fields will be included in the CSV.
- [x] What will the structure of the CSV look like?
- [x] What options, if any, will administration have for outputting specific data?

**Comment by aaronlewis54321** [comment]
[https://app.zenhub.com/files/142712430/7649ddf5-46aa-444d-8bb2-9d92a8982714/download](https://app.zenhub.com/files/142712430/7649ddf5-46aa-444d-8bb2-9d92a8982714/download)

In the above document, I described the process that we can use to pull data from the database, write it to objects in java, and then export it to a csv using a class I found on the internet.
