### ISSUE TITLE
Need to be able to display user data in app

### ISSUE THREAD

**Issue by mrinoldo** [aaronlewis54321/Software_Engineering#20]
- [x] How will we store active users in app for scheduling purposes?
- [x] How often will database be queried to maintain updated user information?
- [x] How will user data be displayed in app? Drop down, table with selectors, ??

**Comment by aaronlewis54321** [comment]
[Need to Be Able to Display User Data in App.docx](https://github.com/aaronlewis54321/Software_Engineering/files/2413398/Need.to.Be.Able.to.Display.User.Data.in.App.docx)
