### ISSUE TITLE
How will admin schedule polling

### ISSUE THREAD

**Issue by mrinoldo** [aaronlewis54321/Software_Engineering#22]
- [x] Will we send a timestamp? UTC?
- [x] How will admin choose schedules?
- [x] How will we transmit?
- [x] Limits on scheduling frequency? 1 min? etc

**Comment by mrinoldo** [comment]
look into Joda-Time... can create intervals, will depend on back-end implementation

**Comment by youngchan1694** [comment]
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html

I believe it Amazon Time Sync Service makes it auto-lock to UTC, but we can also choose the zones (when I say we I mean the backend) within sync service
