### ISSUE TITLE
Consult with product manager about potential use cases for scheduling users

### ISSUE THREAD

**Issue by mrinoldo** [aaronlewis54321/Software_Engineering#26]
- [x] What groupings will need to be made
- [x] Do we need to be able to modify groupings on the fly, once they are created?
- [x] If so, how often will changes be made? (important for deciding how to store users locally)
- [x] How will we store users/groupings locally?

**Comment by youngchan1694** [comment]
Groupings should be up to the admin, and regardless of where/how they're going to be stored, it should be a couple of people in each group, assignable through the admin application itself (probably a drop-down menu for each user)

**Comment by youngchan1694** [comment]
Yes, we should have the ability to create, delete, and edit a group, since having a static grouping is pretty dumb. Also, its more realistic and reliable data if we can randomly assign people different times for different occasions.

**Comment by youngchan1694** [comment]
This grouping is going to be stored locally, so it shouldn't be super difficult or important in terms of how often changes are made. Changes (strictly talking about groups) should be able to be made whenever the admin needs it to be.
