### ISSUE TITLE
Create the setup for the MVC framework 

### ISSUE THREAD

**Issue by empero6** [aaronlewis54321/Software_Engineering#27]
- [x] Create a Bean class for Model, which will be responsible for communication with the database
- [x] Create a View class that controls the components and containers
  - [x] Also create a class for a JFrame and a class for every panel that the project will have
  - [x] The View class will create instances of each of these when it is called from the main class
- [x] Create a controller class, which is where all action lister code will be executed
- [x] Create a driver class, that contains the main file

**Comment by aaronlewis54321** [comment]
I created the framework for the javaFX project, including creating a class for Model, View, and Controller. The view class creates the stage for the main application window, and I also created the basic layout of the application using BorderLayout with VBox's to the left and right, and a table in the middle. I created buttons in the right VBox that will represent different actions that the app must be able to preform that we will have to deal with in the model and controller classes.
