### ISSUE TITLE
Create methods that will be used to help the bean class function

### ISSUE THREAD

**Issue by empero6** [aaronlewis54321/Software_Engineering#28]
Methods should include: 
- [x] Read users from the database and return them in a list, given a specific user and the change that is to be made, communicate the change to the database, read in information from the local database/file, write to CSV, etc.
- [x] Create the method bodies, including return types and parameters for each of these methods

**Comment by aaronlewis54321** [comment]
I was able to create the framework for the methods in the bean class, so the names, parameters, and return types for each one has been determined. I also created a method to test connection to the backend and successfully read from the user database, which will help with actually implementing these methods which we will be able to do in the next sprint
