### ISSUE TITLE
Time Scheduling 

### ISSUE THREAD

**Issue by mbouh1** [aaronlewis54321/Software_Engineering#40]
- [x] Figure out when each user will be sent text messages
- [x] How long does each user have to send text message with emoji back?

**Comment by mrinoldo** [comment]
* Each user that is active in database will have a checkbox allowing them to be selected.
* Each selected group can be given an individual time as scheduled message to send.
* Users will have 10 minutes to respond after which time, they will be reactivated, available for scheduling again.
* Groupings of users will be dynamically chosen, and will not persist
