### ISSUE TITLE
Implement makeUsersInactive method

### ISSUE THREAD

**Issue by mbouh1** [aaronlewis54321/Software_Engineering#46]
Method takes list of user ID that corresponds to people
Creates a list that keeps track of userId that are inactive 
Keeps track of what time inactive IDs are scheduled for

**Comment by youngchan1694** [comment]
public void makeUsersInactive(ArrayList<Person> people)
    {
        ArrayList<String> inactiveUserIds = new ArrayList<String>();
        for(Person p : people) {
            if(p.isActive == false) {
                inactiveUserIds.add(p.getUserID());
            }
        }
    }
