### ISSUE TITLE
Work on design/implementaion of time selection for schedule

### ISSUE THREAD

**Issue by mrinoldo** [aaronlewis54321/Software_Engineering#50]
**User Story**: As it stands, schedule is passed through a text box. Design simpler input for timing, which will translate readable time into UTC ISO 8601 Timestamp.

**Acceptance Criteria**
HTTP connection for updating/creating scheduling will be successful.  Time entered will be passed as schedule for selected users

**Definition of Done
- [x] User's selected will be added to new schedule.
- [ ] Schedule will convert easily read/entered time into ISO 8601 timestamp including date

**Comment by mrinoldo** [comment]
* scheduling is working as expected with text field input. 
* need to implement date/time picker and integrate

**Comment by aaronlewis54321** [comment]
Date and time picker successfully implemented, now the date and time can be input with a selector and then the correct datetime is sent to the database to schedule the selected user
