### ISSUE TITLE
Users need to be made active again 10min after scheduled time

### ISSUE THREAD

**Issue by youngchan1694** [aaronlewis54321/Software_Engineering#52]
Final touches for the functionality

After the initial schedule for users are sent, once the scheduled time is passed, they're pushed back into the list of users ready to be scheduled

If users are displayed in the application after refreshing it at least 10min after their scheduled time, then it is complete

**Comment by aaronlewis54321** [comment]
Now the users automatically become active again 10 minutes after their scheduled time, as described above
