### ISSUE TITLE
Need a method that would save the current state so exiting is possible

### ISSUE THREAD

**Issue by youngchan1694** [aaronlewis54321/Software_Engineering#53]
Realistically, we wouldn't want (or can't) keep the programming running 24/7. Should only open up the application when something needs to be done or checked. However, at this point, when we close the java file the entire state of all the users are reset. We need a method that would write the current state of all the users so that it "saves" for the next time the application is run

**Comment by aaronlewis54321** [comment]
Completed this task by having the application connect to the database and refresh whenever necessary, and write the dates and users are scheduled so that inactive users can be remembered
