### ISSUE TITLE
Figure out the date format for scheduling

### ISSUE THREAD

**Issue by youngchan1694** [aaronlewis54321/Software_Engineering#54]
When the admin wants to schedule a certain for certain users, what is the format the date has to be inputted? Will the format be in ISO 8601, Epoch Converter, etc? GUI-wise, is it going to be a drop down, a textbox that parses it into int, an increment/decrement number box, etc?

**Comment by aaronlewis54321** [comment]
I implemented a drop down list for the date selection, and it is in ISO 8601 format. The GUI now lets the user individually select year, month, day, hour, and minute, and then packages it into a string of the correct format.
