### ISSUE TITLE
CS Department Presentation

### ISSUE THREAD

**Issue by youngchan1694** [aaronlewis54321/Software_Engineering#58]
Communicate with other teams and create a poster for the CS presentation explaining our project to others. Need to figure out format, guidelines, and content of the poster/presentation.

**Comment by youngchan1694** [comment]
Group members should be in class on 11/15 at 5:30PM to work on the poster and talk to other groups in our project

**Comment by aaronlewis54321** [comment]
The poster has been submitted to Dr. Hu for final review, and then the presentation date is on the 30th of  November
