### ISSUE TITLE
Make ourselves available to provide information to other teams

### ISSUE THREAD

**Issue by mrinoldo** [aaronlewis54321/Software_Engineering#9]
- [x] Determine general structure of admin app
- [x] Determine what data we will be exchanging
- [x] Be available for communication with both teams

**Comment by youngchan1694** [comment]
-we have the redrawn conceptual model, with the bubbles representing the aspects and the "actors" representing the places that information going back and forth from
-from database: we need users and responses | to database: send them the message timing (within our local made groups)
-we should be in the megaslack, ive also made a channel on the megaslack for our group!
